version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: cartoon-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: akWAsnmgCwUWQwbV
      MYSQL_DATABASE: cartoons_db
      MYSQL_USER: cartoon_user
      MYSQL_PASSWORD: Kdp8E7V6EU3t0kX6
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: cartoon-flask
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_USER: cartoon_user
      DB_PASSWORD: Kdp8E7V6EU3t0kX6
      DB_HOST: db  
      DB_NAME: cartoons_db

volumes:
  db_data: